# cmake/ChapterBuilder.cmake
function(build_standard_chapter_targets)
    get_filename_component(CHAPTER_DIR_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME)
    string(REPLACE "-" "_" CHAPTER_ID_SAFE ${CHAPTER_DIR_NAME})

    set(CHAPTER_LIB_NAME "${CHAPTER_ID_SAFE}_Lib")
    set(CHAPTER_TARGET_PREFIX "${CHAPTER_ID_SAFE}")

    # --- 数据结构库 ---
    # (与上面模板中类似的 file(GLOB), add_library, target_include_directories, target_link_libraries 逻辑)
    file(GLOB DS_SOURCES RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}/data_structures/src" "data_structures/src/*.cpp")
    if(DS_SOURCES)
        set(DS_FULL_SOURCES "")
        foreach(SOURCE_FILE ${DS_SOURCES})
            list(APPEND DS_FULL_SOURCES "data_structures/src/${SOURCE_FILE}")
        endforeach()
        add_library(${CHAPTER_LIB_NAME} STATIC ${DS_FULL_SOURCES})
        target_include_directories(${CHAPTER_LIB_NAME} PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/data_structures/include>)
        target_link_libraries(${CHAPTER_LIB_NAME} PUBLIC ds_common)
    else()
        message(STATUS "No data structure sources for ${CHAPTER_ID_SAFE}")
    endif()

    # --- 示例 ---
    # (与上面模板中类似的 if(BUILD_EXAMPLES)... 逻辑)
    if(BUILD_EXAMPLES AND EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/examples/src")
        file(GLOB EXAMPLE_SOURCES RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}/examples/src" "examples/src/*.cpp")
        foreach(EXAMPLE_SOURCE_FILE ${EXAMPLE_SOURCES})
            get_filename_component(EXAMPLE_NAME ${EXAMPLE_SOURCE_FILE} NAME_WE)
            add_executable(${CHAPTER_TARGET_PREFIX}_Example_${EXAMPLE_NAME} "examples/src/${EXAMPLE_SOURCE_FILE}")
            target_include_directories(${CHAPTER_TARGET_PREFIX}_Example_${EXAMPLE_NAME} PRIVATE $<IF:$<TARGET:${CHAPTER_LIB_NAME}>,${CMAKE_CURRENT_SOURCE_DIR}/data_structures/include,>)
            if(TARGET ${CHAPTER_LIB_NAME})
                target_link_libraries(${CHAPTER_TARGET_PREFIX}_Example_${EXAMPLE_NAME} PRIVATE ${CHAPTER_LIB_NAME})
            else()
                target_link_libraries(${CHAPTER_TARGET_PREFIX}_Example_${EXAMPLE_NAME} PRIVATE ds_common)
            endif()
        endforeach()
    endif()

    # --- 习题 ---
    # (与上面模板中类似的 if(BUILD_EXERCISES)... 逻辑)
    if(BUILD_EXERCISES AND EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/exercises/src")
        file(GLOB EXERCISE_SOURCES RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}/exercises/src" "exercises/src/*.cpp")
        foreach(EXERCISE_SOURCE_FILE ${EXERCISE_SOURCES})
            get_filename_component(EXERCISE_NAME ${EXERCISE_SOURCE_FILE} NAME_WE)
            add_executable(${CHAPTER_TARGET_PREFIX}_Exercise_${EXERCISE_NAME} "exercises/src/${EXERCISE_SOURCE_FILE}")
            target_include_directories(${CHAPTER_TARGET_PREFIX}_Exercise_${EXERCISE_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/exercises/include $<IF:$<TARGET:${CHAPTER_LIB_NAME}>,${CMAKE_CURRENT_SOURCE_DIR}/data_structures/include,>)
            if(TARGET ${CHAPTER_LIB_NAME})
                target_link_libraries(${CHAPTER_TARGET_PREFIX}_Exercise_${EXERCISE_NAME} PRIVATE ${CHAPTER_LIB_NAME})
            else()
                target_link_libraries(${CHAPTER_TARGET_PREFIX}_Exercise_${EXERCISE_NAME} PRIVATE ds_common)
            endif()
        endforeach()
    endif()

    # if(BUILD_TESTS AND EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/tests")
    #     file(GLOB TEST_SOURCES RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}/" "tests/*.cpp")
    #     foreach(TEST_SOURCES_FILE ${TEST_SOURCES})
    #         get_filename_component(TEST_NAME ${TEST_SOURCES_FILE} NAME_WE)
    #         add_executable(${CHAPTER_TARGET_PREFIX}_Exercise_${TEST_NAME} "${TEST_SOURCES_FILE}")
    #         target_include_directories(${CHAPTER_TARGET_PREFIX}_Exercise_${TEST_NAME} PRIVATE $<IF:$<TARGET:${CHAPTER_LIB_NAME}>,${CMAKE_CURRENT_SOURCE_DIR}/data_structures/include,>)
    #         if(TARGET ${CHAPTER_LIB_NAME})
    #             target_link_libraries(${CHAPTER_TARGET_PREFIX}_Exercise_${TEST_NAME} PRIVATE ${CHAPTER_LIB_NAME})
    #         else()
    #             target_link_libraries(${CHAPTER_TARGET_PREFIX}_Exercise_${TEST_NAME} PRIVATE ds_common)
    #         endif()
    #     endforeach()
    # endif()
endfunction()